# Generated by Django 4.1.1 on 2022-09-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_vendor',
            field=models.CharField(default='customer', max_length=255),
        ),
    ]
