# Generated by Django 4.1.1 on 2022-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
